---
  - hosts: workstation_guests
    vars:
      keyboard_shortcuts:
        cycle-windows: "['<Control><Super><Alt>Tab']"
        cycle-windows-backward: "['<Shift><Control><Super><Alt>Tab']"
        activate-window-menu: "['<Super><Alt>Space']"
        switch-applications: "['<Super><Alt>Tab']"
        switch-applications-backward: "['<Shift><Super><Alt>Tab']"

    tasks:
    - include: configure-git.yml
    - include: docker/install-docker.yml
    - include: install-sga-guard.yml
    - name: "install common packages"
      become: yes
      package:
        name:
          - openssh-server
          - openssh-client
          - autossh
          - ssh-askpass
          - curl
          - python3-psutil
          - tmux
          - htop
          # Provides a remote desktop connection for workstation guests
          - xrdp
          - make
          # https://serverfault.com/questions/214605/gpg-does-not-have-enough-entropy
          # Used for generating entropy when using gpg
          # $ sudo rngd -r /dev/urandom
          - rng-tools

    - name: Set my users authorized keys from Github
      authorized_key:
        user: zee
        state: present
        exclusive: true
        key: https://github.com/zspencer.keys

    - name: "Update keyboard shortcuts"
      loop:  "{{ keyboard_shortcuts|dict2items}}"
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/{{item.key}}"
        value: "{{ item.value | string }}"
        state: present
      when: item.value != ""
    - name: "Ensure xrdp can access the ssh key"
      become: yes
      user:
        name: xrdp
        append: yes
        groups:
          - 'ssl-cert'
    - name: "Allow RDP, SSH and VNC"
      become: yes
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - "22"
        - "5900"
        - "3389"

    - name: "Install VS Code"
      become: yes
      snap:
        name: "code"
        classic: yes
