
---
  - hosts: workstation_hosts
    tasks:
    - include: maintenance/upgrade.yml
    - include: maintenance/ssh-connectivity.yml
    - include: development-environment/terminal.yml
    - include: push-launch-scripts.yml
    - include: docker/install-docker.yml
