
---
  - hosts: cli_workstations
    tasks:
    - include: maintenance/upgrade.yml
    - include: maintenance/remote-management.yml
    - include: maintenance/performance-monitoring.yml
    - include: development-environment/terminal.yml
