---
  - hosts: workstation_guests
    vars:
      keyboard_shortcuts:
        cycle-windows: "['<Control><Super><Alt>Tab']"
        cycle-windows-backward: "['<Shift><Control><Super><Alt>Tab']"
        activate-window-menu: "['<Super><Alt>Space']"
        switch-applications: "['<Super><Alt>Tab']"
        switch-applications-backward: "['<Shift><Super><Alt>Tab']"

    tasks:
    - include: maintenance/upgrade.yml
    - include: maintenance/remote-management.yml
    - include: maintenance/performance-monitoring.yml
    - include: development-environment/terminal.yml
    - include: development-environment/desktop.yml

    - name: Set my users authorized keys from Github
      authorized_key:
        user: zee
        state: present
        exclusive: true
        key: https://github.com/zspencer.keys

    - name: "Update keyboard shortcuts"
      loop:  "{{ keyboard_shortcuts|dict2items}}"
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/{{item.key}}"
        value: "{{ item.value | string }}"
        state: present
      when: item.value != ""

    - name: "Install VS Code"
      become: yes
      snap:
        name: "code"
        classic: yes
