
---
  - hosts: workstation_hosts
    tasks:
    - include: maintenance/upgrade.yml
    - include: maintenance/ssh-connectivity.yml
    - include: push-launch-scripts.yml
    - include: configure-git.yml
    - include: docker/install-docker.yml
