#!/bin/bash
MY_OPTIONS="+pcid,+ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check"

OVMF="./OSX-KVM"

qemu-system-x86_64 -enable-kvm -m 48G \
	-cpu Penryn,kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on,$MY_OPTIONS \
	-machine q35 \
	-smp 8,sockets=1,cores=4,threads=2\
	-device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc" \
	-drive if=pflash,format=raw,readonly,file=$OVMF/OVMF_CODE.fd \
	-drive if=pflash,format=raw,file=$OVMF/OVMF_VARS-1024x768.fd \
	-smbios type=2 \
	-device ich9-intel-hda -device hda-duplex \
	-device ich9-ahci,id=sata \
	-drive id=Clover,if=none,snapshot=on,format=qcow2,file=./'disks/catalina-clover-ng.qcow2' \
	-device ide-hd,bus=sata.2,drive=Clover \
	-drive id=MacHDD,if=none,file=./disks/catalina.img,format=qcow2 \
	-device ide-hd,bus=sata.4,drive=MacHDD \
	-device vfio-pci,host=01:00.0,multifunction=on \
	-device vfio-pci,host=01:00.1 \
	-usb \
	-device usb-host,vendorid=0xc0f3,productid=0x02a1 \
	-device usb-host,vendorid=0x1b1c,productid=0x1b50 \
	-device usb-host,vendorid=0x046d,productid=0xc539 \
	-netdev user,id=net0 -device vmxnet3,netdev=net0,id=net0,mac=52:54:00:c9:18:27 \
	-rtc clock=host,base=localtime \
	-vga none \
	-nographic

# Installation Media
#	-drive id=InstallMedia,if=none,file=BaseSystem.img,format=raw \
#	-device ide-hd,bus=sata.3,drive=InstallMedia \

#  OVMF
# OVMF=./firmware
