---
- hosts: all
  become: yes
  tasks:
  - name: Create my user
    user:
      name: zee
      comment: Zee Spencer
      shell: /bin/bash
      groups: sudo
  - name: Set my users authorized keys from Github
    authorized_key:
      user: zee
      state: present
      exclusive: true
      key: https://github.com/zspencer.keys