---
- hosts: all
  remote_user: root
  tasks:
  - name: Create my user
    user:
      name: zee
      comment: Zee Spencer
      groups: sudo
  - name: Set my users authorized keys from Github
    authorized_key:
      user: zee
      state: present
      exclusive: true
      key: https://github.com/zspencer.keys
  - name: Set roots authorized keys from my Github
    authorized_key:
      user: root
      state: present
      exclusive: true
      key: https://github.com/zspencer.keys
