- name: "Get Tailscales GPG Key in our Apt Keychain"
  become: yes
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/focal.gpg
    state: present

- name: "Add Tailscales Repo to our Sources"
  become: yes
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/ubuntu focal main
    state: present

- name: "Install Tailscale"
  become: yes
  package:
    name: tailscale
